# -*- coding: utf-8 -*-
"""Code_Along16_TFIDF.ipynb

Automatically generated by Colab.

"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

recipe_names= [
              'Spicy Chicken Tacos',
              'Vegetarian Pasta',
              'Chocolate Chip Cookie',
              'Rice Pudding',
              'Shepherd Pie'

]

vectorizer=TfidfVectorizer()

tfid_matrix=vectorizer.fit_transform(recipe_names)

df_tfid=pd.DataFrame(data=tfid_matrix.toarray(), columns=vectorizer.get_feature_names_out(), index=recipe_names)
print(df_tfid)

