# -*- coding: utf-8 -*-
"""Code_Along15_Adidas_ts.ipynb

Automatically generated by Colab.
"""

import pandas as pd
from datetime import date, timedelta
import datetime
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_pacf
from statsmodels.tsa.arima_model import ARIMA
import statsmodels.api as sm

import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("adidas-quarterly-sales.csv")

df.head()

df.tail()

df.columns

df.shape

df.isnull().values.sum()

df.info()

df.describe

import plotly.express as px
figure = px.line(df, x="Time Period", y= "Revenue",
                 title="Quarterly Sales Revenie of Adidas (in Millions)")
figure.show()

model=sm.tsa.statespace.SARIMAX(df['Revenue'])

# Fit the model
model=model.fit()

predictions = model.predict(len(df), len(df)+7)
print(predictions)

df['Revenue'].plot(legend = True,
                   label= 'Training Data',
                   figsize=(15,10))
predictions.plot(legend = True, label = "Predictions")

