
"""CodeAlong2 - Review

Automatically generated by Colab.

Created August 28, 2023
"""

# Variables
msg = "Hello!"
f_name = "albert"
l_name = "einstein"
full_name = f_name + ' ' + l_name
print(full_name)

# Lists
# Making a list
bikes = ['trek', 'redline', 'giant']
print(bikes)

first_bike = bikes[0]
print(first_bike)

last_bike = bikes[2]  # Can be 2 or -1 to access the last item in the list
last_bike_other_way = bikes[-1]
print(last_bike)
print(last_bike_other_way)

for bike in bikes:
    print(bike)

bikes = []
bikes.append('trek')  # Append adds to list
bikes.append('redline')
bikes.append('giant')
bikes.append('mountain')

print(bikes)

squares = []
for x in range(1, 11):  # 1-10
    squares.append(x**2)
print(squares)

# Slicing a list
finishers = ['sam', 'bob', 'ada', 'bea']
first_two = finishers[0:2]  # Gives you items 0 and 1 in the list
# : means start so can also use [:2] instead of [0:2]
print(first_two)

# Tuples
# Keeps it in memory - similar to lists
# Making a tuple
dimensions = (1920, 800)

# Numbers
x = 1
y = 2.8
z = "Hello!"

print(type(x))
print(type(y))  # Prints the data type
print(type(z))

# Make a number a string by using quotation marks

a = float(x)  # Change x to a float
print(a)
print(type(a))

b = int(y)
print(b)
print(type(b))

msg = "hello!"
print(msg)

msg.lower()
msg.upper()

# Fahrenheit to Celsius
current_fahrenheit = 100
celsius = (current_fahrenheit - 32) * 5 / 9
print("The Celsius equivalent is: ", celsius)

# Comparison operators
x = 10
y = 15

print('is x > y:', x > y)
print('is x < y:', x < y)
print('is x equal to y:', x == y)
print('is x not equal to y:', x != y)
print('is x >= y:', x >= y)
print('is x <= y:', x <= y)

# If Statements
age = 25

if age > 18:
    print("You can vote!")

age = 18

if age < 7:
    ticket_price = 0
elif age < 18:
    ticket_price = 10
else:
    ticket_price = 15

print(ticket_price)
