# -*- coding: utf-8 -*-
"""llms_questions.ipynb

Automatically generated by Colab.


"""

!pip install openai

!pip install tiktoken

!pip install PyPDF2

!pip install faiss-cpu

!pip install langchain

from PyPDF2 import PdfReader
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain import FAISS
from langchain.chains.question_answering import load_qa_chain
from langchain.llms import OpenAI
from langchain.callbacks import get_openai_callback
import os
import openai
os.environ["OPENAI_API_KEY"] = "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"

def process_text(text):
  # split the text into chunks using langchain
  text_splitter = CharacterTextSplitter(
      separator="\n",
      chunk_size=1000,
      chunk_overlap=200,
      length_function=len
  )
  chunks = text_splitter.split_text(text)

  # convert the chunks of text into embeddings to form a knowledge base
  embeddings = OpenAIEmbeddings()
  knowledgeBase = FAISS.from_texts(chunks, embeddings)
  return knowledgeBase

pdf_reader = PdfReader('ai_ethics.pdf')

text = ""
for page in pdf_reader.pages:
  text += page.extract_text()

# create the knowledge base object
knowledgeBase = process_text (text)

def question(query):
  docs = knowledgeBase.similarity_search(query)
  llm = OpenAI()
  chain = load_qa_chain(llm, chain_type = 'stuff')
  with get_openai_callback() as cost:
    response = chain.run(input_documents=docs, question=query)
  print(response)

question('What is ai ethics?')