# -*- coding: utf-8 -*-
"""TakeHomeExam2.ipynb

Automatically generated by Colab.


"""

# import numpy
# import pandas
import numpy as np
import pandas as pd

pwd

pwd

# Read File
df = pd.read_csv('Stores.csv')
df
dff = pd.DataFrame(df)

df.info()

df.head()

df.tail()

# Columns
df['Store_Area']

# Drop a row by index (e.g., row 1)
index_to_drop = 1
df = df.drop(index_to_drop)

# Display the DataFrame after dropping the row
print("\nDataFrame after dropping row {}: ".format(index_to_drop))
print(df)

# ADD ROW


new_row = {'Store ID': 1010, 'Store_Area': 1566, 'Items_Available': 2000, 'Daily_Customer': 600, 'Store_Sales': 88000}

# Add the new row using the 'loc' indexer
df = dff.append(new_row, ignore_index=True)

df

# DROP COLUMN


# drop 'Daily_Customer_Count'
column_to_drop = 'Daily_Customer_Count'

df.columns = df.columns.str.strip()
df = dff.drop(column_to_drop, axis=1)


# (optional): Save the modified DataFrame back to a CSV file
df.to_csv('modified_csv_file.csv', index=False)
df



# ADD COLUMN

employee_counts = [800] * 895

# Add the new column to the DataFrame
df['Employee_Count'] = employee_counts

# Display the DataFrame after adding the new column
print("\nDataFrame after adding column 'Employee_Count':")
print(df)



# gives first two rows
df.iloc[0:2]