# -*- coding: utf-8 -*-
"""TakeHomeExam1.ipynb

Automatically generated by Colab.


"""

# import Numpy & Pandas
import numpy as np
import pandas as pd

# Array 1-7
arr1 = np.array([1,2,3,4,5,6,7])

# Array of 7 zeros
arr7zeros = np.zeros(7)

# Array of 7 tens
arr7tens = np.full(7,10)

# Have an array of odd numbers between 0 through 23
arrodd = np.arange(1,24,2)

# Turn above array into 4x3 matrix
matrix = arrodd.reshape(4,3)
matrix

# Generate random integer numbers between 1 -25
import random
random_num = random.randint(1,25)
print(random_num)

# Generate pandas dataframe similar to result below
data = {'Column 1': matrix[:, 0], 'Column 2': matrix[:, 1], 'Column 3': matrix[:, 2]}
df = pd.DataFrame(data)
df



df = df.rename(columns={'Column 1': 'Item'})
df = df.rename(columns={'Column 2': 'Quantity'})
df = df.rename(columns={'Column 3': 'Price'})
df

df.loc[df['Item'] == 1, 'Item'] = 'Apples'
df.loc[df['Item'] == 7, 'Item'] = 'Bread'
df.loc[df['Item'] == 13, 'Item'] = 'Milk'
df.loc[df['Item'] == 19, 'Item'] = 'Eggs'
df.loc[df['Item'] == 5, 'Item'] = 'Celery'
df

new_row = {'Item': 'Celery', 'Quantity': 1, 'Price': 0.99}
df = df.append(new_row, ignore_index= True)
df

index_remove = 5
df = df.drop(index_remove)
df

df['Quantity']= [3,2,1,1,1]
df['Price']= [1.99,2.49,1.29,2.99,0.99]
df

df.loc[df['Item'] == 'apple', 'Item'] = 'Apples'
df